[package]
name = "filesender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
chrono = "0.4.19"
env_logger = "0.9.0"
colored = "2.0.0"
tokio = {version = "1", features = ["full"]}

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[lib]
name = "shared"
path = "src/shared/lib.rs"
